<!--
  Términos de uso. Igual que la página de privacidad: ruta en castellano, texto
  en inglés, y nada que no sea verdad de esta app.

  Se dicen las tres cosas incómodas: que corre en una sola instancia y un deploy
  te corta la sesión, que el modelo se equivoca, y que la clave del proveedor es
  una sola y por eso hay topes.
-->
<svelte:head>
	<title>Terms · Lost in Translation</title>
</svelte:head>

<header class="cabecera tapa">
	<a class="etiqueta volver" href="/">← Back</a>
	<p class="etiqueta num">Last updated 2026-09-24</p>
</header>

<main class="hoja tapa">
	<h1 class="titular">Terms.</h1>
	<p class="bajada">
		A personal project, free, by invitation, for practising English. Not a school, not a product, no
		certificate at the end. Here is what that means in practice.
	</p>

	<section class="bloque">
		<h2 class="sub">Your account</h2>
		<p>
			One account per person, tied to the Google account you sign in with. Don't share it — the
			daily allowances below are per account, and so is your review schedule, which stops being
			useful the moment two people answer through it.
		</p>
		<p>You can delete the account whenever you want, from the home screen. No one has to approve it.</p>
	</section>

	<section class="bloque">
		<h2 class="sub">Fair use of the AI</h2>
		<p>
			The tutor and the speaking practice both cost real money per request, and they run on a single
			API key. That is why there is a cap on how many you get per day, a cap on the total for
			everyone, and a limit on how fast requests can arrive. When the daily budget runs out, the AI
			turns itself off and the rest of the app keeps working.
		</p>
		<p>
			Scripting the API, or deliberately burning the budget so nobody else can practise, ends the
			invitation.
		</p>
	</section>

	<section class="bloque">
		<h2 class="sub">Who owns what</h2>
		<p>
			The lessons, exercises, explanations and the design are the author's work. Use them to study;
			don't republish them as your own.
		</p>
		<p>
			What you answer and what you record is yours. You can download all of it as a file at any
			time, and it leaves with you when you delete the account.
		</p>
	</section>

	<section class="bloque">
		<h2 class="sub">It can be wrong, and it can be down</h2>
		<p>
			Exercises are graded by rules, so grading is predictable. The tutor's explanations are
			generated by a language model and can be confidently wrong. Treat them as a study aid, not as
			an authority — and never as the basis for an exam, a visa, a contract or anything else that
			matters.
		</p>
		<p>
			This runs on one small server. A deploy interrupts whoever is studying at that moment, and
			outages happen. There is no uptime promise and no support desk. Back-ups are not guaranteed
			yet: if your progress matters to you, export it.
		</p>
	</section>

	<section class="bloque">
		<h2 class="sub">Ending it</h2>
		<p>
			You can leave at any time by deleting your account. The author can close the app, or remove an
			account that breaks these terms — barring abuse, with enough notice to export your data first.
		</p>
	</section>

	<section class="bloque">
		<h2 class="sub">Changes</h2>
		<p>
			These terms change as the app does. The date at the top of this page says when they last did.
			Anything that changes what happens to your data is described on the privacy page as well.
		</p>
	</section>

	<p class="etiqueta"><a href="/privacidad">Privacy →</a></p>
</main>

<style>
	.cabecera {
		display: flex;
		justify-content: space-between;
		align-items: center;
		gap: 12px;
		min-height: 44px;
		border-bottom: 1px solid var(--line);
	}

	.volver {
		text-decoration: none;
		display: inline-flex;
		align-items: center;
		min-height: 44px;
	}

	.hoja {
		display: grid;
		gap: 28px;
		max-width: 68ch;
		padding-block: calc(var(--module) * 1.5) calc(var(--module) * 3);
	}

	p {
		margin: 0;
	}

	.titular {
		font-size: clamp(40px, 8vw, 56px);
	}

	.bajada {
		font-size: 20px;
		line-height: 1.45;
		font-weight: 500;
	}

	.bloque {
		display: grid;
		gap: 12px;
		padding-top: 20px;
		border-top: 1px solid var(--line);
	}

	.sub {
		margin: 0;
		font-size: 24px;
		font-weight: 700;
		letter-spacing: -0.02em;
	}

	a {
		color: inherit;
	}

	.etiqueta a {
		text-decoration: none;
	}

	.etiqueta a:hover {
		color: var(--baranda);
	}
</style>
