// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

// Borra la cuenta. El resto lo hace el ON DELETE CASCADE de las migraciones:
// cada tabla con datos de una persona referencia users(id). La única excepción
// es ai_answers, que es una caché global por hash de prompt y no tiene user_id;
// está dicho en la página de privacidad.
func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccountAttempts = `-- name: ListAccountAttempts :many
SELECT id, user_id, item_id, skill_id, context, placement_run_id, response, correct, latency_ms, created_at, consulted FROM attempts WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListAccountAttempts(ctx context.Context, userID pgtype.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAccountAttempts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.SkillID,
			&i.Context,
			&i.PlacementRunID,
			&i.Response,
			&i.Correct,
			&i.LatencyMs,
			&i.CreatedAt,
			&i.Consulted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountCards = `-- name: ListAccountCards :many
SELECT user_id, item_id, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review FROM cards WHERE user_id = $1 ORDER BY item_id
`

func (q *Queries) ListAccountCards(ctx context.Context, userID pgtype.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, listAccountCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.UserID,
			&i.ItemID,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountDailyLog = `-- name: ListAccountDailyLog :many
SELECT user_id, day, colada, answers, seconds FROM daily_log WHERE user_id = $1 ORDER BY day
`

func (q *Queries) ListAccountDailyLog(ctx context.Context, userID pgtype.UUID) ([]DailyLog, error) {
	rows, err := q.db.Query(ctx, listAccountDailyLog, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyLog
	for rows.Next() {
		var i DailyLog
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.Colada,
			&i.Answers,
			&i.Seconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountLessonProgress = `-- name: ListAccountLessonProgress :many
SELECT user_id, skill_id, status, started_at, completed_at FROM lesson_progress WHERE user_id = $1 ORDER BY skill_id
`

func (q *Queries) ListAccountLessonProgress(ctx context.Context, userID pgtype.UUID) ([]LessonProgress, error) {
	rows, err := q.db.Query(ctx, listAccountLessonProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonProgress
	for rows.Next() {
		var i LessonProgress
		if err := rows.Scan(
			&i.UserID,
			&i.SkillID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountPlacementRuns = `-- name: ListAccountPlacementRuns :many

SELECT id, user_id, part, content_version, status, started_at, finished_at FROM placement_runs WHERE user_id = $1 ORDER BY started_at, id
`

// Las consultas de exportación traen la fila entera a propósito: exportar tiene
// que devolver todo lo que la app guarda de esa persona, así que agregar una
// columna a una tabla la agrega también a la exportación sin que haya que
// acordarse de tocar acá.
func (q *Queries) ListAccountPlacementRuns(ctx context.Context, userID pgtype.UUID) ([]PlacementRun, error) {
	rows, err := q.db.Query(ctx, listAccountPlacementRuns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlacementRun
	for rows.Next() {
		var i PlacementRun
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Part,
			&i.ContentVersion,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountSkillMastery = `-- name: ListAccountSkillMastery :many
SELECT user_id, skill_id, mastery, state, source, updated_at FROM skill_mastery WHERE user_id = $1 ORDER BY skill_id
`

func (q *Queries) ListAccountSkillMastery(ctx context.Context, userID pgtype.UUID) ([]SkillMastery, error) {
	rows, err := q.db.Query(ctx, listAccountSkillMastery, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillMastery
	for rows.Next() {
		var i SkillMastery
		if err := rows.Scan(
			&i.UserID,
			&i.SkillID,
			&i.Mastery,
			&i.State,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountUsage = `-- name: ListAccountUsage :many
SELECT user_id, day, kind, n FROM usage_daily WHERE user_id = $1 ORDER BY day, kind
`

func (q *Queries) ListAccountUsage(ctx context.Context, userID pgtype.UUID) ([]UsageDaily, error) {
	rows, err := q.db.Query(ctx, listAccountUsage, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageDaily
	for rows.Next() {
		var i UsageDaily
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.Kind,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
