// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantAchievements = `-- name: GrantAchievements :exec
INSERT INTO achievements (user_id, code)
SELECT $1::uuid, unnest($2::text[])
ON CONFLICT (user_id, code) DO NOTHING
`

type GrantAchievementsParams struct {
	UserID pgtype.UUID
	Codes  []string
}

// Todos los códigos en un solo INSERT, dentro de la transacción que escribió el
// progreso que los causó. El ON CONFLICT DO NOTHING es la regla del dominio: lo
// ganado no se vuelve a ganar ni se pierde, así que earned_at es el día de la
// primera vez y no se toca nunca más.
func (q *Queries) GrantAchievements(ctx context.Context, arg GrantAchievementsParams) error {
	_, err := q.db.Exec(ctx, grantAchievements, arg.UserID, arg.Codes)
	return err
}

const listAchievements = `-- name: ListAchievements :many
SELECT user_id, code, earned_at FROM achievements WHERE user_id = $1
`

func (q *Queries) ListAchievements(ctx context.Context, userID pgtype.UUID) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(&i.UserID, &i.Code, &i.EarnedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
