// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlacementRun = `-- name: CreatePlacementRun :one
INSERT INTO placement_runs (user_id, part, content_version)
VALUES ($1, $2, $3)
RETURNING id, user_id, part, content_version, status, started_at, finished_at
`

type CreatePlacementRunParams struct {
	UserID         pgtype.UUID
	Part           string
	ContentVersion string
}

func (q *Queries) CreatePlacementRun(ctx context.Context, arg CreatePlacementRunParams) (PlacementRun, error) {
	row := q.db.QueryRow(ctx, createPlacementRun, arg.UserID, arg.Part, arg.ContentVersion)
	var i PlacementRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Part,
		&i.ContentVersion,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishPlacementRun = `-- name: FinishPlacementRun :exec
UPDATE placement_runs
SET status = 'done', finished_at = now()
WHERE id = $1
`

func (q *Queries) FinishPlacementRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, finishPlacementRun, id)
	return err
}

const getCard = `-- name: GetCard :one
SELECT user_id, item_id, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review FROM cards WHERE user_id = $1 AND item_id = $2
`

type GetCardParams struct {
	UserID pgtype.UUID
	ItemID string
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, arg.UserID, arg.ItemID)
	var i Card
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.LastReview,
	)
	return i, err
}

const getOpenPlacementRun = `-- name: GetOpenPlacementRun :one
SELECT id, user_id, part, content_version, status, started_at, finished_at FROM placement_runs
WHERE user_id = $1 AND part = $2 AND status = 'in_progress'
`

type GetOpenPlacementRunParams struct {
	UserID pgtype.UUID
	Part   string
}

func (q *Queries) GetOpenPlacementRun(ctx context.Context, arg GetOpenPlacementRunParams) (PlacementRun, error) {
	row := q.db.QueryRow(ctx, getOpenPlacementRun, arg.UserID, arg.Part)
	var i PlacementRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Part,
		&i.ContentVersion,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getPlacementRun = `-- name: GetPlacementRun :one
SELECT id, user_id, part, content_version, status, started_at, finished_at FROM placement_runs
WHERE id = $1 AND user_id = $2
`

type GetPlacementRunParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetPlacementRun(ctx context.Context, arg GetPlacementRunParams) (PlacementRun, error) {
	row := q.db.QueryRow(ctx, getPlacementRun, arg.ID, arg.UserID)
	var i PlacementRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Part,
		&i.ContentVersion,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getPlacementRunForUpdate = `-- name: GetPlacementRunForUpdate :one
SELECT id, user_id, part, content_version, status, started_at, finished_at FROM placement_runs
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetPlacementRunForUpdateParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetPlacementRunForUpdate(ctx context.Context, arg GetPlacementRunForUpdateParams) (PlacementRun, error) {
	row := q.db.QueryRow(ctx, getPlacementRunForUpdate, arg.ID, arg.UserID)
	var i PlacementRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Part,
		&i.ContentVersion,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :one
INSERT INTO attempts (user_id, item_id, skill_id, context, placement_run_id, response, correct, latency_ms, consulted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertAttemptParams struct {
	UserID         pgtype.UUID
	ItemID         string
	SkillID        string
	Context        string
	PlacementRunID pgtype.UUID
	Response       []byte
	Correct        bool
	LatencyMs      pgtype.Int4
	Consulted      bool
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAttempt,
		arg.UserID,
		arg.ItemID,
		arg.SkillID,
		arg.Context,
		arg.PlacementRunID,
		arg.Response,
		arg.Correct,
		arg.LatencyMs,
		arg.Consulted,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLatestPlacementRuns = `-- name: ListLatestPlacementRuns :many
SELECT DISTINCT ON (part) id, user_id, part, content_version, status, started_at, finished_at
FROM placement_runs
WHERE user_id = $1
ORDER BY part, started_at DESC
`

// La corrida más reciente de cada parte.
func (q *Queries) ListLatestPlacementRuns(ctx context.Context, userID pgtype.UUID) ([]PlacementRun, error) {
	rows, err := q.db.Query(ctx, listLatestPlacementRuns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlacementRun
	for rows.Next() {
		var i PlacementRun
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Part,
			&i.ContentVersion,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunAttempts = `-- name: ListRunAttempts :many
SELECT item_id, skill_id, correct, consulted
FROM attempts
WHERE placement_run_id = $1
ORDER BY id
`

type ListRunAttemptsRow struct {
	ItemID    string
	SkillID   string
	Correct   bool
	Consulted bool
}

func (q *Queries) ListRunAttempts(ctx context.Context, placementRunID pgtype.UUID) ([]ListRunAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listRunAttempts, placementRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunAttemptsRow
	for rows.Next() {
		var i ListRunAttemptsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.SkillID,
			&i.Correct,
			&i.Consulted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillMastery = `-- name: ListSkillMastery :many
SELECT user_id, skill_id, mastery, state, source, updated_at FROM skill_mastery WHERE user_id = $1
`

func (q *Queries) ListSkillMastery(ctx context.Context, userID pgtype.UUID) ([]SkillMastery, error) {
	rows, err := q.db.Query(ctx, listSkillMastery, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillMastery
	for rows.Next() {
		var i SkillMastery
		if err := rows.Scan(
			&i.UserID,
			&i.SkillID,
			&i.Mastery,
			&i.State,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCard = `-- name: UpsertCard :exec
INSERT INTO cards (user_id, item_id, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id, item_id) DO UPDATE
SET due = EXCLUDED.due,
    stability = EXCLUDED.stability,
    difficulty = EXCLUDED.difficulty,
    elapsed_days = EXCLUDED.elapsed_days,
    scheduled_days = EXCLUDED.scheduled_days,
    reps = EXCLUDED.reps,
    lapses = EXCLUDED.lapses,
    state = EXCLUDED.state,
    last_review = EXCLUDED.last_review
`

type UpsertCardParams struct {
	UserID        pgtype.UUID
	ItemID        string
	Due           pgtype.Timestamptz
	Stability     float64
	Difficulty    float64
	ElapsedDays   int32
	ScheduledDays int32
	Reps          int32
	Lapses        int32
	State         int16
	LastReview    pgtype.Timestamptz
}

func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) error {
	_, err := q.db.Exec(ctx, upsertCard,
		arg.UserID,
		arg.ItemID,
		arg.Due,
		arg.Stability,
		arg.Difficulty,
		arg.ElapsedDays,
		arg.ScheduledDays,
		arg.Reps,
		arg.Lapses,
		arg.State,
		arg.LastReview,
	)
	return err
}

const upsertSkillMastery = `-- name: UpsertSkillMastery :exec
INSERT INTO skill_mastery (user_id, skill_id, mastery, state, source, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id, skill_id) DO UPDATE
SET mastery = EXCLUDED.mastery,
    state = EXCLUDED.state,
    source = EXCLUDED.source,
    updated_at = now()
`

type UpsertSkillMasteryParams struct {
	UserID  pgtype.UUID
	SkillID string
	Mastery float32
	State   string
	Source  string
}

func (q *Queries) UpsertSkillMastery(ctx context.Context, arg UpsertSkillMasteryParams) error {
	_, err := q.db.Exec(ctx, upsertSkillMastery,
		arg.UserID,
		arg.SkillID,
		arg.Mastery,
		arg.State,
		arg.Source,
	)
	return err
}
