// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID
	FirebaseUid string
	Email       string
	DisplayName string
	Theme       string
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}
