// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiAnswer struct {
	ID         int64
	PromptHash string
	Question   string
	Context    string
	Answer     string
	Model      string
	CreatedAt  pgtype.Timestamptz
}

type AiUsage struct {
	UserID pgtype.UUID
	Day    pgtype.Date
	Asks   int32
}

type Attempt struct {
	ID             int64
	UserID         pgtype.UUID
	ItemID         string
	SkillID        string
	Context        string
	PlacementRunID pgtype.UUID
	Response       []byte
	Correct        bool
	LatencyMs      pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	Consulted      bool
}

type Card struct {
	UserID        pgtype.UUID
	ItemID        string
	Due           pgtype.Timestamptz
	Stability     float64
	Difficulty    float64
	ElapsedDays   int32
	ScheduledDays int32
	Reps          int32
	Lapses        int32
	State         int16
	LastReview    pgtype.Timestamptz
}

type DailyLog struct {
	UserID  pgtype.UUID
	Day     pgtype.Date
	Colada  int32
	Answers int32
	Seconds int32
}

type LessonProgress struct {
	UserID      pgtype.UUID
	SkillID     string
	Status      string
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type PlacementRun struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Part           string
	ContentVersion string
	Status         string
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

type SkillMastery struct {
	UserID     pgtype.UUID
	SkillID    string
	Mastery    float32
	State      string
	Source     string
	UpdatedAt  pgtype.Timestamptz
	WasCalzada bool
}

type User struct {
	ID          pgtype.UUID
	FirebaseUid string
	Email       string
	DisplayName string
	Theme       string
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}
