// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tutor.sql

package store

import (
	"context"
)

const getCachedAnswer = `-- name: GetCachedAnswer :one
SELECT answer, model FROM ai_answers WHERE prompt_hash = $1
`

type GetCachedAnswerRow struct {
	Answer string
	Model  string
}

func (q *Queries) GetCachedAnswer(ctx context.Context, promptHash string) (GetCachedAnswerRow, error) {
	row := q.db.QueryRow(ctx, getCachedAnswer, promptHash)
	var i GetCachedAnswerRow
	err := row.Scan(&i.Answer, &i.Model)
	return i, err
}

const saveAnswer = `-- name: SaveAnswer :exec
INSERT INTO ai_answers (prompt_hash, question, context, answer, model)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (prompt_hash) DO NOTHING
`

type SaveAnswerParams struct {
	PromptHash string
	Question   string
	Context    string
	Answer     string
	Model      string
}

func (q *Queries) SaveAnswer(ctx context.Context, arg SaveAnswerParams) error {
	_, err := q.db.Exec(ctx, saveAnswer,
		arg.PromptHash,
		arg.Question,
		arg.Context,
		arg.Answer,
		arg.Model,
	)
	return err
}
