// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUsage = `-- name: AddUsage :exec
INSERT INTO usage_daily (user_id, day, kind, n)
VALUES ($1, current_date, $2, 1)
ON CONFLICT (user_id, day, kind) DO UPDATE SET n = usage_daily.n + 1
`

type AddUsageParams struct {
	UserID pgtype.UUID
	Kind   string
}

func (q *Queries) AddUsage(ctx context.Context, arg AddUsageParams) error {
	_, err := q.db.Exec(ctx, addUsage, arg.UserID, arg.Kind)
	return err
}

const countUsageToday = `-- name: CountUsageToday :one
SELECT COALESCE((
    SELECT n FROM usage_daily
    WHERE user_id = $1 AND day = current_date AND kind = $2
), 0)::int
`

type CountUsageTodayParams struct {
	UserID pgtype.UUID
	Kind   string
}

func (q *Queries) CountUsageToday(ctx context.Context, arg CountUsageTodayParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUsageToday, arg.UserID, arg.Kind)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsageTodayAll = `-- name: CountUsageTodayAll :one
SELECT COALESCE(sum(n), 0)::int FROM usage_daily
WHERE day = current_date AND kind = $1
`

func (q *Queries) CountUsageTodayAll(ctx context.Context, kind string) (int32, error) {
	row := q.db.QueryRow(ctx, countUsageTodayAll, kind)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
