// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, display_name, theme, created_at, last_seen_at FROM users WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateUserTheme = `-- name: UpdateUserTheme :one
UPDATE users
SET theme = $2
WHERE firebase_uid = $1
RETURNING id, firebase_uid, email, display_name, theme, created_at, last_seen_at
`

type UpdateUserThemeParams struct {
	FirebaseUid string
	Theme       string
}

func (q *Queries) UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTheme, arg.FirebaseUid, arg.Theme)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (firebase_uid, email, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (firebase_uid) DO UPDATE
SET email        = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    last_seen_at = now()
RETURNING id, firebase_uid, email, display_name, theme, created_at, last_seen_at
`

type UpsertUserParams struct {
	FirebaseUid string
	Email       string
	DisplayName string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.FirebaseUid, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
