// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeWalletChallenge = `-- name: ConsumeWalletChallenge :one
DELETE FROM wallet_challenges
WHERE user_id = $1 AND nonce = $2 AND expires_at > now()
RETURNING nonce
`

type ConsumeWalletChallengeParams struct {
	UserID pgtype.UUID
	Nonce  string
}

// Comparar y borrar en la misma sentencia es lo que hace al nonce de un solo
// uso de verdad. Si fueran dos consultas —leer, verificar, borrar— dos pedidos
// simultáneos con el mismo nonce pasarían los dos. Y el vencimiento lo decide
// el reloj de Postgres, no el del proceso: si hay dos réplicas, tienen que
// estar de acuerdo.
func (q *Queries) ConsumeWalletChallenge(ctx context.Context, arg ConsumeWalletChallengeParams) (string, error) {
	row := q.db.QueryRow(ctx, consumeWalletChallenge, arg.UserID, arg.Nonce)
	var nonce string
	err := row.Scan(&nonce)
	return nonce, err
}

const getAchievementEarned = `-- name: GetAchievementEarned :one
SELECT earned_at FROM achievements WHERE user_id = $1 AND code = $2
`

type GetAchievementEarnedParams struct {
	UserID pgtype.UUID
	Code   string
}

// La única pregunta que el voucher necesita hacerle a la verdad: ¿está ganado?
// Se lee de la tabla, no se recalcula, porque una pieza oxidada después sigue
// teniendo su distinción.
func (q *Queries) GetAchievementEarned(ctx context.Context, arg GetAchievementEarnedParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getAchievementEarned, arg.UserID, arg.Code)
	var earned_at pgtype.Timestamptz
	err := row.Scan(&earned_at)
	return earned_at, err
}

const getMint = `-- name: GetMint :one
SELECT user_id, code, address, chain_id, token_id, tx_hash, status, updated_at FROM mints WHERE user_id = $1 AND code = $2
`

type GetMintParams struct {
	UserID pgtype.UUID
	Code   string
}

func (q *Queries) GetMint(ctx context.Context, arg GetMintParams) (Mint, error) {
	row := q.db.QueryRow(ctx, getMint, arg.UserID, arg.Code)
	var i Mint
	err := row.Scan(
		&i.UserID,
		&i.Code,
		&i.Address,
		&i.ChainID,
		&i.TokenID,
		&i.TxHash,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT user_id, address, chain_id, verified_at FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.UserID,
		&i.Address,
		&i.ChainID,
		&i.VerifiedAt,
	)
	return i, err
}

const linkWallet = `-- name: LinkWallet :one
INSERT INTO wallets (user_id, address, chain_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET address = EXCLUDED.address, chain_id = EXCLUDED.chain_id, verified_at = now()
RETURNING user_id, address, chain_id, verified_at
`

type LinkWalletParams struct {
	UserID  pgtype.UUID
	Address string
	ChainID int32
}

// Vincular de nuevo pisa la dirección anterior de esa persona. El UNIQUE de la
// tabla sigue estando: si la dirección ya es de otro, esto falla y tiene que
// fallar.
func (q *Queries) LinkWallet(ctx context.Context, arg LinkWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, linkWallet, arg.UserID, arg.Address, arg.ChainID)
	var i Wallet
	err := row.Scan(
		&i.UserID,
		&i.Address,
		&i.ChainID,
		&i.VerifiedAt,
	)
	return i, err
}

const listMints = `-- name: ListMints :many
SELECT user_id, code, address, chain_id, token_id, tx_hash, status, updated_at FROM mints WHERE user_id = $1
`

func (q *Queries) ListMints(ctx context.Context, userID pgtype.UUID) ([]Mint, error) {
	rows, err := q.db.Query(ctx, listMints, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mint
	for rows.Next() {
		var i Mint
		if err := rows.Scan(
			&i.UserID,
			&i.Code,
			&i.Address,
			&i.ChainID,
			&i.TokenID,
			&i.TxHash,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putWalletChallenge = `-- name: PutWalletChallenge :exec
INSERT INTO wallet_challenges (user_id, nonce, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET nonce = EXCLUDED.nonce, expires_at = EXCLUDED.expires_at
`

type PutWalletChallengeParams struct {
	UserID    pgtype.UUID
	Nonce     string
	ExpiresAt pgtype.Timestamptz
}

// Un desafío por persona: pedir uno nuevo pisa el anterior. Así nadie puede
// juntar nonces válidos y usarlos más tarde.
func (q *Queries) PutWalletChallenge(ctx context.Context, arg PutWalletChallengeParams) error {
	_, err := q.db.Exec(ctx, putWalletChallenge, arg.UserID, arg.Nonce, arg.ExpiresAt)
	return err
}

const recordMint = `-- name: RecordMint :one
INSERT INTO mints (user_id, code, address, chain_id, tx_hash, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
ON CONFLICT (user_id, code) DO UPDATE
SET tx_hash = EXCLUDED.tx_hash, address = EXCLUDED.address,
    chain_id = EXCLUDED.chain_id, updated_at = now()
WHERE mints.status <> 'confirmed'
RETURNING user_id, code, address, chain_id, token_id, tx_hash, status, updated_at
`

type RecordMintParams struct {
	UserID  pgtype.UUID
	Code    string
	Address string
	ChainID int32
	TxHash  pgtype.Text
}

// El txHash entra como 'pending' antes de preguntarle nada al RPC. Si el nodo
// no contesta, el dato ya está guardado y la confirmación se reintenta: lo que
// nunca puede pasar es perder el hash de una transacción que la persona ya pagó.
// Una distinción ya confirmada no vuelve atrás por un txHash nuevo: el token
// existe y el id es determinista, así que no hay segundo minteo posible.
func (q *Queries) RecordMint(ctx context.Context, arg RecordMintParams) (Mint, error) {
	row := q.db.QueryRow(ctx, recordMint,
		arg.UserID,
		arg.Code,
		arg.Address,
		arg.ChainID,
		arg.TxHash,
	)
	var i Mint
	err := row.Scan(
		&i.UserID,
		&i.Code,
		&i.Address,
		&i.ChainID,
		&i.TokenID,
		&i.TxHash,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const settleMint = `-- name: SettleMint :one
UPDATE mints
SET status = $3, token_id = $4::numeric, updated_at = now()
WHERE user_id = $1 AND code = $2
RETURNING user_id, code, address, chain_id, token_id, tx_hash, status, updated_at
`

type SettleMintParams struct {
	UserID  pgtype.UUID
	Code    string
	Status  string
	TokenID pgtype.Numeric
}

// Lo que dijo el recibo. token_id viaja como texto y se convierte acá porque un
// uint256 no entra en ningún entero de Go.
func (q *Queries) SettleMint(ctx context.Context, arg SettleMintParams) (Mint, error) {
	row := q.db.QueryRow(ctx, settleMint,
		arg.UserID,
		arg.Code,
		arg.Status,
		arg.TokenID,
	)
	var i Mint
	err := row.Scan(
		&i.UserID,
		&i.Code,
		&i.Address,
		&i.ChainID,
		&i.TokenID,
		&i.TxHash,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkWallet = `-- name: UnlinkWallet :execrows
DELETE FROM wallets WHERE user_id = $1
`

// Desvincula de este lado y nada más: en la cadena no hay nada que borrar.
func (q *Queries) UnlinkWallet(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkWallet, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
