<script lang="ts">
	import { goto } from '$app/navigation';
	import { api, ApiError, type Distincion } from '$lib/api';
	import { session } from '$lib/session.svelte';
	import { hayBilletera, wallet } from '$lib/wallet.svelte';

	let todas = $state<Distincion[]>([]);
	let error = $state<string | null>(null);
	let loading = $state(true);

	// La cadena es opcional en la interfaz, no sólo en el discurso: sin
	// configuración en el servidor, `chain` viene en false y esta pantalla se ve
	// exactamente igual que antes de que todo esto existiera.
	let cadena = $state(false);

	$effect(() => {
		if (!session.ready) return;
		if (!session.user) {
			goto('/');
			return;
		}
		load();
	});

	async function load() {
		try {
			todas = (await api.achievements()).achievements;
		} catch (err) {
			error =
				err instanceof ApiError
					? `${err.status} · ${err.message}`
					: 'No se pudieron cargar las distinciones.';
		} finally {
			loading = false;
		}
		// Después de lo importante: que el servidor tenga o no una cadena no
		// puede demorar en aparecer la lista.
		try {
			cadena = (await api.health()).chain === true;
		} catch {
			cadena = false;
		}
		if (cadena) await wallet.cargar();
	}

	const acortar = (a: string) => `${a.slice(0, 6)}…${a.slice(-4)}`;

	/** El texto del botón según lo que se sepa de esa distinción en la cadena. */
	function estadoDe(code: string): { etiqueta: string; reclamable: boolean } {
		const m = wallet.mint(code);
		if (m?.status === 'confirmed') return { etiqueta: 'Minted', reclamable: false };
		if (m?.status === 'pending') return { etiqueta: 'Confirming…', reclamable: false };
		if (wallet.reclamando === code) return { etiqueta: 'Claiming…', reclamable: false };
		// Un intento fallido se puede volver a intentar: el logro sigue ganado.
		return { etiqueta: m?.status === 'failed' ? 'Try again' : 'Claim', reclamable: true };
	}

	type Grupo = { obra: number; obraName: string; piezas: Distincion[]; entera: Distincion | null };

	// El servidor ya las manda en orden de currículum: las piezas de cada obra y
	// después la obra. Acá sólo se agrupan, sin reordenar nada.
	const grupos = $derived(
		todas.reduce<Grupo[]>((acc, d) => {
			let g = acc.at(-1);
			if (!g || g.obra !== d.obra) {
				g = { obra: d.obra, obraName: d.obraName, piezas: [], entera: null };
				acc.push(g);
			}
			if (d.kind === 'obra') g.entera = d;
			else g.piezas.push(d);
			return acc;
		}, [])
	);

	const ganadas = $derived(todas.filter((d) => d.earned).length);

	const formato = new Intl.DateTimeFormat('en-GB', {
		day: '2-digit',
		month: 'short',
		year: 'numeric'
	});
	const cuando = (iso: string | null) => (iso ? formato.format(new Date(iso)) : '');
</script>

<header class="cabecera tapa">
	<a class="etiqueta volver" href="/map">← Tu obra</a>
	<p class="etiqueta num">{ganadas} / {todas.length} distinciones</p>
</header>

<main class="distinciones tapa">
	{#if error}
		<p class="error" role="alert">{error}</p>
	{:else if loading}
		<p class="etiqueta">Loading</p>
	{:else}
		<h1 class="titular">Distinciones.</h1>
		<p class="bajada lectura">
			One for every topic you set in place, one for every obra you finish. A piece can rust later
			and the distinction stays: it records that you got there, not that you're still there.
		</p>

		{#if cadena}
			<!-- La cadena es el recibo, no la verdad: todo lo de arriba y lo de
			     abajo funciona igual sin esto. -->
			<section class="cadena">
				{#if wallet.direccion}
					<div class="vinculada">
						<p class="etiqueta">Wallet linked</p>
						<p class="num dir" title={wallet.direccion}>{acortar(wallet.direccion)}</p>
						<button class="texto" onclick={() => wallet.desconectar()}>Unlink</button>
					</div>
					<p class="letra-chica lectura">
						Unlinking only removes the wallet from this account. Anything you already minted stays
						on the blockchain, belongs to that address, and cannot be deleted by anyone.
					</p>
				{:else}
					<p class="lectura">
						Every distinction you earned can also be minted as a token that outlives this app: a
						soulbound ERC-721 whose drawing is your own piece, generated by the contract itself.
						Only your address and a piece number ever reach the blockchain — no email, no name, no
						progress — and what is minted cannot be deleted.
					</p>
					{#if hayBilletera()}
						<button class="accion" onclick={() => wallet.conectar()} disabled={wallet.conectando}>
							{wallet.conectando ? 'Waiting for your wallet…' : 'Connect wallet'}
						</button>
					{:else}
						<p class="letra-chica">
							No browser wallet found. Install one to claim your distinctions on-chain.
						</p>
					{/if}
				{/if}
				{#if wallet.error}
					<p class="error" role="alert">{wallet.error}</p>
				{/if}
			</section>
		{/if}

		{#each grupos as grupo (grupo.obra)}
			<section class="obra">
				<header class="rotulo">
					<p class="etiqueta">Obra {grupo.obra} · {grupo.obraName}</p>
					{#if grupo.piezas.length > 0}
						<p class="etiqueta num">
							{grupo.piezas.filter((p) => p.earned).length} / {grupo.piezas.length}
						</p>
					{/if}
				</header>

				{#if grupo.piezas.length === 0}
					<p class="vacia">No pieces drawn yet — this obra is still on paper.</p>
				{:else}
					<ul class="piezas">
						{#each grupo.piezas as pieza (pieza.code)}
							<li class="pieza" class:ganada={pieza.earned}>
								<span class="nombre">{pieza.nameEn}</span>
								<span class="es">{pieza.nameEs}</span>
								<span class="fecha num">{pieza.earned ? cuando(pieza.earnedAt) : 'Not yet'}</span>
								{#if cadena && pieza.earned && wallet.direccion}
									{@const estado = estadoDe(pieza.code)}
									<button
										class="reclamar num"
										disabled={!estado.reclamable}
										onclick={() => wallet.reclamar(pieza.code)}
									>
										{estado.etiqueta}
									</button>
								{/if}
							</li>
						{/each}
					</ul>
				{/if}

				{#if grupo.entera}
					<div class="entera" class:ganada={grupo.entera.earned}>
						<span class="etiqueta">The whole obra</span>
						<span class="nombre">{grupo.entera.nameEn}</span>
						<span class="fecha num">
							{grupo.entera.earned ? cuando(grupo.entera.earnedAt) : 'Every piece has to set'}
						</span>
						{#if cadena && grupo.entera.earned && wallet.direccion}
							{@const estado = estadoDe(grupo.entera.code)}
							{@const code = grupo.entera.code}
							<button
								class="reclamar num"
								disabled={!estado.reclamable}
								onclick={() => wallet.reclamar(code)}
							>
								{estado.etiqueta}
							</button>
						{/if}
					</div>
				{/if}
			</section>
		{/each}
	{/if}
</main>

<style>
	.cabecera {
		display: flex;
		justify-content: space-between;
		align-items: center;
		gap: 12px;
		min-height: 44px;
		border-bottom: 1px solid var(--line);
	}

	.volver {
		text-decoration: none;
		display: inline-flex;
		align-items: center;
		min-height: 44px;
	}

	.distinciones {
		display: grid;
		gap: 24px;
		padding-block: calc(var(--module) * 1.5) calc(var(--module) * 3);
	}

	p {
		margin: 0;
	}

	.titular {
		font-size: clamp(40px, 8vw, 56px);
	}

	.bajada {
		font-size: 18px;
		color: var(--text-muted);
	}

	/* La sección de la cadena: un bloque aparte, con el borde del andamio, para
	   que se lea como algo que se le agregó a la obra y no como parte de ella. */
	.cadena {
		display: grid;
		gap: 12px;
		justify-items: start;
		padding: 16px 18px;
		border: 1.25px solid var(--line-soft);
		border-left: var(--tensor) solid var(--baranda);
	}

	.cadena p {
		font-size: 15px;
		color: var(--text-muted);
	}

	.vinculada {
		display: flex;
		align-items: center;
		flex-wrap: wrap;
		gap: 12px;
	}

	.dir {
		font-family: var(--font-mono);
		font-size: 14px;
		color: var(--text);
	}

	.letra-chica {
		font-size: 13px;
	}

	.accion {
		min-height: 44px;
		padding: 0 18px;
		border: 1.25px solid var(--line);
		background: var(--hormigon-luz);
		color: var(--vano);
		cursor: pointer;
	}

	.accion:hover:not(:disabled) {
		border-color: var(--baranda);
	}

	.accion:disabled {
		cursor: progress;
		opacity: 0.6;
	}

	.texto {
		min-height: 44px;
		padding: 0;
		border: 0;
		background: none;
		color: var(--text-muted);
		text-decoration: underline;
		text-underline-offset: 3px;
		cursor: pointer;
	}

	/* El botón de reclamar vive adentro de la pieza ya ganada, así que va sobre
	   hormigón y con la tipografía de los rótulos. */
	.reclamar {
		justify-self: start;
		margin-top: 8px;
		min-height: 32px;
		padding: 0 10px;
		border: 1.25px solid var(--vano);
		background: none;
		color: var(--vano);
		font-size: 12px;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		cursor: pointer;
	}

	.reclamar:disabled {
		border-style: dashed;
		opacity: 0.6;
		cursor: default;
	}

	.obra {
		display: grid;
		gap: 10px;
		padding-top: var(--module);
	}

	.rotulo {
		display: flex;
		justify-content: space-between;
		align-items: baseline;
		gap: 12px;
		border-bottom: 1px solid var(--line-soft);
		padding-bottom: 6px;
	}

	.vacia {
		color: var(--text-muted);
		font-size: 15px;
	}

	.piezas {
		list-style: none;
		margin: 0;
		padding: 0;
		display: grid;
		gap: 10px;
		grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
	}

	/* El mismo lenguaje del pilar: lo que falta va en línea punteada y lo ganado
	   apoya en hormigón. */
	.pieza,
	.entera {
		display: grid;
		gap: 2px;
		padding: 12px 14px;
		border: 1.25px dashed var(--line);
		color: var(--text-muted);
	}

	.pieza.ganada,
	.entera.ganada {
		border-style: solid;
		background: var(--hormigon-luz);
		color: var(--vano);
	}

	.entera {
		margin-top: 4px;
		border-width: 2px;
	}

	.entera.ganada {
		border-color: var(--baranda);
	}

	/* Sobre el hormigón el rótulo tiene que leerse igual que el resto */
	.entera.ganada .etiqueta {
		color: var(--vano);
		opacity: 0.7;
	}

	.nombre {
		font-weight: 600;
		line-height: 1.3;
	}

	.es {
		font-size: 14px;
		opacity: 0.8;
	}

	.fecha {
		font-family: var(--font-mono);
		font-size: 12px;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		opacity: 0.75;
	}

	.error {
		color: var(--oxido);
	}
</style>
